### ISSUE TITLE
Variables not properly injected in Symfony's "bind" feature in dev env ?

### ISSUE THREAD

**Issue by hiromik** [vlucas/phpdotenv#289]
Hello,

I recently migrated a Symfony 2.8 app to 3.4 and took advantage of the ["bind" feature](https://symfony.com/blog/new-in-symfony-3-4-local-service-binding).
My env parameters are loaded using a `.env` file 

`MY_PARAMETER=OK`

and a `parameters.php` which does 
 
```$container->setParameter('my_parameter', getenv('MY_PARAMETER'));```

 `parameters.php` is imported through `config.yml` using 
```
imports:
    - { resource: parameters.yml }
```
These are then bind in `services.yml` using : 
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $myParameter: '%my_parameter%'
```

Somehow the autowired services that have `$myParameter` as a constructor's argument receive the `'ok' `value properly in production environment (`app.php`), as soon as I switch to dev or add `app_dev.php` to url the injected value becomes empty `''`

Any idea ?
